# Generated by Django 4.2.7 on 2023-12-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
